export function errorToUserCodeFailure(err, nonRetryable) {
    if (typeof err === 'string') {
        return { message: err };
    }
    if (err instanceof Error) {
        return { message: err.message, type: err.name, stackTrace: err.stack, nonRetryable };
    }
    // Default value
    return { message: 'Unknown error' };
}
/**
 * Helper for creating promises which can be manually resolved
 */
export class ResolvablePromise {
    constructor() {
        const promise = new Promise((resolve, reject) => {
            // @ts-ignore
            this.resolve = resolve;
            // @ts-ignore
            this.reject = reject;
        });
        this.then = promise.then.bind(promise);
    }
}
